version: '3'
services:
    app:
        build:
            context: /app/
        volumes: 
         - ./app:/app
        ports:
         - '3000:3000'
        restart: always
    app:
        build:
            context: /nginx/
        ports:
            - '80:80'