version: '3'
services:
    app:
        build:
            context: ./app/
        volumes: 
            - ./app:/app
        ports:
            - '3000:3000'
        restart: always
    nginx:
        build:
            context: ./nginx/
        ports:
            - '80:80'
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot